Refactoring: adding support for profiles
Cleanup

diff --git a/freckles/bootstrap/freckles b/freckles/bootstrap/freckles
--- a/freckles/bootstrap/freckles
+++ b/freckles/bootstrap/freckles
@@ -52,6 +52,8 @@ fi
 # General variables
 DEBUG=false
 
+PROFILE_NAME="frkl"
+
 FRECKLES_USER_HOME="`eval echo ~$FRECKLES_USER`"
 
 BASE_DIR="$FRECKLES_USER_HOME/.freckles"
@@ -63,18 +65,8 @@ TEMP_DIR="/tmp/freckles_install"
 FRECKLES_PATH="$BASE_DIR/bin"
 
 # python/virtualenv related variables
-VIRTUALENV_DIR="$FRECKLES_DATA_DIR/venv_freckles"
+VIRTUALENV_DIR="$FRECKLES_DATA_DIR/venv_$PROFILE_NAME"
 VIRTUALENV_PATH="$VIRTUALENV_DIR/bin"
-
-# nix-related variables
-PROOT_DIR="$BASE_DIR/opt/proot"
-PROOT_EXE="$PROOT_DIR/proot-x86_64"
-NIX_DIR="$BASE_DIR/opt/nix"
-NIX_ROOT="$NIX_DIR/root"
-NIX_ROOT_INSTALL_SCRIPT="https://raw.githubusercontent.com/makkus/ansible-nix-single/master/files/install_nix.sh"
-NIX_NON_ROOT_INSTALL_SCRIPT="https://raw.githubusercontent.com/makkus/ansible-nix-single/master/files/install_nix_proot.sh"
-NIX_SRC_STORE_DIR="$BASE_DIR/nix"
-NIX_ENV_EXE="$HOME/.nix-profile/bin/nix-env"
 
 # conda related variables
 CONDA_DOWNLOAD_URL_LINUX="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
@@ -84,15 +76,21 @@ CONDA_DOWNLOAD_URL_MAC="https://repo.continuum.io/miniconda/Miniconda2-latest-Ma
 CONDA_BASE_DIR="$BASE_DIR/opt/conda"
 CONDA_PATH="$CONDA_BASE_DIR/bin"
 CONDA_ROOT_EXE="$CONDA_BASE_DIR/bin/conda"
-CONDA_FRECKLES_ENV_PATH="$CONDA_BASE_DIR/envs/freckles"
+CONDA_FRECKLES_ENV_PATH="$CONDA_BASE_DIR/envs/$PROFILE_NAME"
 CONDA_FRECKLES_ENV_EXE="$CONDA_FRECKLES_ENV_PATH/bin/conda"
-STOW_SRC_DOWNLOAD_URL="http://ftp.gnu.org/gnu/stow/stow-2.2.2.tar.gz"
 
-# deb related variables
-DEB_DEPENDENCIES="build-essential git python-dev python-virtualenv libssl-dev libffi-dev stow"
-
-# rpm related variables
-RPM_DEPENDENCIES="epel-release wget git python-virtualenv stow openssl-devel stow gcc libffi-devel python-devel openssl-devel"
+# profile dependent
+# conda
+CONDA_PYTHON_VERSION="2.7"
+CONDA_DEPENDENCIES="pip git"
+CONDA_PKGS_EXIST_CHECK_PATH="$CONDA_FRECKLES_ENV_PATH/bin/git"
+CONDA_EXECUTABLES_TO_LINK="$PROFILE_NAME"
+# deb
+DEB_DEPENDENCIES="build-essential git python-dev python-virtualenv libssl-dev libffi-dev"
+# rpm
+RPM_DEPENDENCIES="epel-release wget git python-virtualenv openssl-devel stow gcc libffi-devel python-devel openssl-devel"
+# pip requirements
+PIP_DEPENDENCIES="pyyaml frkl"
 
 mkdir -p "$INSTALL_LOG_DIR"
 touch "$SCRIPT_LOG_FILE"
@@ -101,14 +99,16 @@ chown "$FRECKLES_USER" "$SCRIPT_LOG_FILE"
 
 function log () {
     echo "    .. $@" >> "$SCRIPT_LOG_FILE"
-    if [[ ! -z $FRECKLES_VERBOSE ]]; then
-        echo "    .. $@"
-    fi
 }
 
+function output() {
+    log $@
+    echo "$@"
+}
 
-function nix_execute {
-    PATH=$NIX_PATH:$PATH $PROOT_EXE -b $NIX_ROOT:/nix $@
+function error_output() {
+    log $1
+    echo "$@"
 }
 
 function command_exists {
@@ -126,7 +126,7 @@ function download {
     elif command_exists curl; then
         execute_log "curl -o $2 $1" "Could not download $1 using curl"
     else
-        echo "Could not find 'wget' nor 'curl' to download files. Exiting..."
+        error_output "Could not find 'wget' nor 'curl' to download files. Exiting..."
         exit 1
     fi
     } >> "$SCRIPT_LOG_FILE"
@@ -142,7 +142,6 @@ function install_freckles {
 
 #TODO: exception handline for this
 function create_virtualenv {
-    echo "  - creating virtualenv for freckles"
     {
     su "$FRECKLES_USER" <<EOF
 set +e
@@ -156,44 +155,51 @@ pip install --upgrade setuptools wheel
 pip install --upgrade requests
 set -e
 EOF
-    } >> "$SCRIPT_LOG_FILE" 2>&1 || error_exit "Could not create freckles virtual environment"
+    } >> "$SCRIPT_LOG_FILE" 2>&1 || error_exit "Could not create '$PROFILE_NAME' virtual environment"
 }
 
 #TODO: exception handling for this
-function install_freckles_in_virtualenv {
-    echo "  - installing freckles into virtualenv"
+#TODO: check whether package already installed? or overkill? -- yeah, probably
+function install_package_in_virtualenv {
+    output "  * installing '$1' into virtualenv"
     {
         su "$FRECKLES_USER" <<EOF
 set +e
 source "$VIRTUALENV_DIR/bin/activate"
-pip install --upgrade freckles --upgrade-strategy only-if-needed
+pip install --upgrade "$1" --upgrade-strategy only-if-needed
 set -e
 EOF
-    } >> "$SCRIPT_LOG_FILE" 2>&1 || error_exit "Could not create freckles virtual environment"
+    } >> "$SCRIPT_LOG_FILE" 2>&1 || error_exit "Could not create '$PROFILE_NAME' virtual environment"
 }
 
 
 function install_freckles_deb {
-    echo -e "  * Debian-based system detected"
-    log "Updating apt cache"
+    output "  * Debian-based system detected"
+    output "  * updating apt cache"
     execute_log "apt-get update" "Could not update apt repository cache"
-    echo -e "  - Installing dependencies:\n\t$DEB_DEPENDENCIES"
-    execute_log "apt-get install -y build-essential git python-dev python-virtualenv libssl-dev libffi-dev stow" "Error installing dependencies via apt."
-    log "Creating freckles virtual environment"
+    output "  * installing dependencies:\n\t$DEB_DEPENDENCIES"
+    execute_log "apt-get install -y $DEB_DEPENDENCIES" "Error installing dependencies via apt."
+    output "  * creating '$PROFILE_NAME' virtual environment"
     create_virtualenv
-    install_freckles_in_virtualenv
+    for pkgName in $PIP_DEPENDENCIES
+    do
+        install_package_in_virtualenv $pkgName
+    done
     link_required_executables "$VIRTUALENV_PATH"
     export PATH="$PATH:$VIRTUALENV_PATH"
 }
 
 function install_freckles_rpm {
-    echo "  * RedHat-based system detected."
-    echo -e "  - Installing dependencies:\n\t$RPM_DEPENDENCIES"
+    output "  * RedHat-based system detected."
+    output "  * installing dependencies:\n\t$RPM_DEPENDENCIES"
     execute_log "yum install -y epel-release" "Error installing dependencies via yum."
     execute_log "yum install -y $RPM_DEPENDENCIES" "Error installing dependencies via yum."
-    log "Creating freckles virtual environment"
+    output "  * creating '$PROFILE_NAME' virtual environment"
     create_virtualenv
-    install_freckles_in_virtualenv
+    for pkgName in $PIP_DEPENDENCIES
+    do
+        install_package_in_virtualenv $pkgName
+    done
     link_required_executables "$VIRTUALENV_PATH"
     export PATH="$PATH:$VIRTUALENV_PATH"
 }
@@ -201,7 +207,7 @@ function install_freckles_rpm {
 function install_xcode {
     g++ --version > /dev/null 2&>1
     if [ ! $? == 0 ]; then
-        echo -e "  - Installing xcode"
+        output "  * installing xcode"
         touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
         log "Finding command-line-tools name"
         PROD=$(softwareupdate -l |
@@ -212,35 +218,16 @@ function install_xcode {
         log "Installing: $PROD"
         execute_log "softwareupdate -i \"$PROD\" -v" "Could not install $PROD"
     else
-        echo -e "  - 'xcode' already installed, skipping"
+        output "  - 'xcode' already installed, skipping"
     fi
 
-}
-
-function install_stow_from_source {
-    if ! command_exists stow; then
-        echo -e "  - Installing 'stow' from source"
-        rm -rf /tmp/stow_install
-        mkdir -p /tmp/stow_install
-        cd /tmp/stow_install || error_exit "Can't enter stow download dir"
-        download "$STOW_SRC_DOWNLOAD_URL" "/tmp/stow_install/stow.tar.gz"
-        execute_log "tar xvzf /tmp/stow_install/stow.tar.gz" "Could not untar stow tar file"
-        execute_log "rm /tmp/stow_install/stow.tar.gz" "Could not delete downloaded stow file"
-        cd stow*
-        execute_log ./configure "Could not configure stow sources"
-        execute_log "sudo make install" "Could not install stow"
-        cd ~
-        execute_log "sudo rm -rf /tmp/stow_install" "Could not delete stow sources"
-    else
-        echo -e "  - 'stow' already installed, skilling"
-    fi
 }
 
 function install_freckles_mac_root {
-    echo "  * MacOS X-based system detected."
+    output "  * MacOS X-based system detected."
     install_xcode
     install_stow_from_source
-    echo -e "  - Installing pip & virtualenv"
+    output "  * installing pip & virtualenv"
     if ! command_exists pip; then
         execute_log "easy_install pip" "Could not install pip"
     fi
@@ -248,9 +235,12 @@ function install_freckles_mac_root {
         execute_log "pip install virtualenv" "Could not install virtualenv via pip"
     fi
 
-    log "Creating freckles virtual environment"
+    output "  * creating '$PROFILE_NAME' virtual environment"
     create_virtualenv
-    install_freckles_in_virtualenv
+    for pkgName in $PIP_DEPENDENCIES
+    do
+        install_package_in_virtualenv $pkgName
+    done
     link_required_executables "$VIRTUALENV_PATH"
     export PATH="$PATH:$VIRTUALENV_PATH"
 }
@@ -263,12 +253,14 @@ function install_freckles_linux_root {
     elif [[ ! -z $APT_GET_CMD ]]; then
         install_freckles_deb
     else
-        echo "Could not find supported package manager. Exiting..."
+        error_output "Could not find supported package manager. Exiting..."
         exit 6
     fi
 }
 
 function install_freckles_root {
+
+    output "  * elevated permissions detected, using sytem package manager to install dependencies"
 
     # figure out which os we are running
     if [[ "$OSTYPE" == "linux-gnu"* ]]; then
@@ -277,20 +269,20 @@ function install_freckles_root {
         install_freckles_mac_root
     elif [[ "$OSTYPE" == "cygwin" ]]; then
         # POSIX compatibility layer and Linux environment emulation for Windows
-        echo "Sorry, Cygwin platform is not supported (at the moment, anyway). Exiting..."
+        error_output "Sorry, Cygwin platform is not supported (at the moment, anyway). Exiting..."
         exit 6
     elif [[ "$OSTYPE" == "msys" ]]; then
         # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
-        echo "Sorry, msys/MinGW platform is not supported (at the moment, anyway). Exiting..."
+        error_output "Sorry, msys/MinGW platform is not supported (at the moment, anyway). Exiting..."
         exit 6
     elif [[ "$OSTYPE" == "win32" ]]; then
-        echo "Sorry, win32 platform is not supported (at the moment, anyway). Exiting..."
+        error_output "Sorry, win32 platform is not supported (at the moment, anyway). Exiting..."
         exit 6
     elif [[ "$OSTYPE" == "freebsd"* ]]; then
-        echo "Sorry, freebsd platform is not supported (at the moment, anyway). Exiting..."
+        error_output "Sorry, freebsd platform is not supported (at the moment, anyway). Exiting..."
         exit 6
     else
-        echo "Could not figure out which platform I'm running on. Exiting..."
+        error_output "Could not figure out which platform I'm running on. Exiting..."
         exit 6
     fi
 }
@@ -301,70 +293,62 @@ function link_path {
 }
 
 function link_required_executables {
-    link_path "$1" freckles
-    link_path "$1" stow
-    link_path "$1" git
-    link_path "$1" ansible-playbook
-    link_path "$1" ansible-galaxy
+    for pkgName in $CONDA_EXECUTABLES_TO_LINK
+    do
+      link_path "$1" "$pkgName"
+    done
 }
-
 
 function install_freckles_non_root_conda {
 
-    echo "  * no elevated permissions detected, using conda package manager"
+    output "  * no elevated permissions detected, using conda package manager"
 
     if [ ! -f "$CONDA_ROOT_EXE" ]; then
-        echo "  * installing conda"
+        output "  * installing conda"
         install_conda_non_root
     else
-        echo "  * 'conda' already installed, not installing again"
+        output "  - 'conda' already installed, not installing again"
         export PATH="$CONDA_PATH:$PATH"
     fi
 
-    echo "  - installing freckles and its requirements (this will take a bit)"
-
-    if [ ! -f "$CONDA_FRECKLES_ENV_EXE" ]; then
-        log "Creating freckles conda environment"
-        execute_log "conda create -y --name freckles python=2" "Could not create conda environment."
+    if [ ! -e "$CONDA_FRECKLES_ENV_EXE" ]; then
+        output "  * creating '$PROFILE_NAME' conda environment"
+        execute_log "conda create -y --name $PROFILE_NAME python=2" "Could not create conda environment."
     else
-        log "freckles conda environment already exists, not creating again"
+        output "  - '$PROFILE_NAME' conda environment already exists, not creating again"
     fi
 
-    if [ ! -f "$CONDA_FRECKLES_ENV_PATH/bin/git" ]; then
-        log "Installing python into conda environment"
-        execute_log "conda install --name freckles -y python=2.7" "Could not install python in conda environment."
-        log "Installing pip into conda environment"
-        execute_log "conda update --name freckles -y pip" "Could not install pip in conda environment."
-        log "Installing git into conda environment"
-        execute_log "conda install --name freckles -y git" "Could not install git in conda environment."
-        log "Installing cryptography into conda environment"
-        execute_log "conda install --name freckles -y cryptography" "Could not install cryptography in conda environment."
-        log "Installing pycrypto into conda environment"
-        execute_log "conda install --name freckles -y pycrypto" "Could not install pycrypto in conda environment."
-        # I know this is stupid, but without this the Ubuntu on Window bootstrapping didn't work
-        execute_log "conda install --name freckles -y cryptography" "Could not install cryptography in conda environment."
-        log "Installing git into conda environment"
-        execute_log "conda install --name freckles -y git" "Could not install git in conda environment."
+    if [ ! -e "$CONDA_PKGS_EXIST_CHECK_PATH" ]; then
+        output "  * installing python (version $CONDA_PYTHON_VERSION) into conda environment"
+        execute_log "conda install --name $PROFILE_NAME -y python=$CONDA_PYTHON_VERSION" "Could not install python in conda environment."
+        for pkgName in $CONDA_DEPENDENCIES
+        do
+                output "  * installing $pkgName into conda environment"
+                execute_log "conda install --name $PROFILE_NAME -y $pkgName" "Could not install $pkgName in conda environment."
+        done
     else
-        log "Base freckles requirements already installed, not installing again."
+        output "  - base requirements already installed, not installing again"
     fi
 
-    if [ ! -f "$CONDA_FRECKLES_ENV_PATH/bin/stow" ]; then
-        log "Installing stow into conda environment"
-        execute_log "conda install --name freckles -y -c conda-forge -c freckles stow" "Could not install stow or one of its dependencies via conda."
-    else
-        log "'stow' requirement already installed, not installing again."
-    fi
+    execute_log "source activate $PROFILE_NAME" "Could not activate '$PROFILE_NAME' conda environment"
 
-    execute_log "source activate freckles" "Could not activate freckles virtual environment"
-    log "Installing freckles"
-    execute_log "pip install -U freckles --upgrade-strategy only-if-needed" "Could not install freckles in conda environment"
-    execute_log "source deactivate freckles" "Could not deactivate freckles virtual environment"
-    link_required_executables "$CONDA_BASE_DIR/envs/freckles/bin"
+    for pkgName in $PIP_DEPENDENCIES
+    do
+        modules=`pydoc modules`
+        if echo "$modules" | grep -q "$pkgName" ; then
+           output "  - python package '$pkgName' already installed in conda environment '$PROFILE_NAME'"
+        else
+           output "  * installing python package '$pkgName' into conda environment '$PROFILE_NAME'"
+           execute_log "pip install -U $pkgName --upgrade-strategy only-if-needed" "Could not install $pkgName in conda environment"
+        fi
+
+    done
+    execute_log "source deactivate $PROFILE_NAME" "Could not deactivate '$PROFILE_NAME' conda environment"
+    link_required_executables "$CONDA_BASE_DIR/envs/$PROFILE_NAME/bin"
 }
 
 function install_conda_non_root {
-    echo "  - bootstrapping conda package manager"
+    output "  * bootstrapping conda package manager"
     {
     cd "$TEMP_DIR"
     if [[ "$OSTYPE" == "linux-gnu" ]]; then
@@ -374,7 +358,7 @@ function install_conda_non_root {
     fi
     } >> "$SCRIPT_LOG_FILE" 2>&1
     mkdir -p "$FRECKLES_DATA_DIR"
-    echo "  - installing conda"
+    output "  * installing conda"
     {
     bash "$TEMP_DIR/miniconda.sh" -b -p "$CONDA_BASE_DIR"
     export PATH="$CONDA_PATH:$PATH"
@@ -382,7 +366,6 @@ function install_conda_non_root {
     rm -rf "$TEMP_DIR"
     } >> "$SCRIPT_LOG_FILE" 2>&1
 }
-
 
 function add_freckles_path {
 
@@ -396,9 +379,9 @@ if [ -d "$FRECKLES_PATH" ]; then
 fi
 EOF
 
-       echo -e "\nAdded path to freckles bin dir to .profile. You'll need to logout and login again to see the effect. Or you can just execute:\n\n  source $HOME/.profile"
-       echo
-       echo
+       output "\nAdded path to freckles bin dir to .profile. You'll need to logout and login again to see the effect. Or you can just execute:\n\n  source $HOME/.profile"
+       output ""
+       output ""
     fi
 }
 
@@ -407,7 +390,7 @@ EOF
 execute_log "echo Starting freckles bootstrap: `date`" "Error"
 
 # check if freckles is already in the path, if it is, assume everything is bootstrapped
-if ! command_exists freckles; then
+if ! command_exists $1; then
     mkdir -p "$TEMP_DIR"
     mkdir -p "$FRECKLES_PATH"
     if [ $using_sudo == true ]; then
@@ -416,20 +399,22 @@ if ! command_exists freckles; then
         chown -R "$FRECKLES_USER" "$FRECKLES_PATH"
     fi
 
-    echo -e "\n'freckles' not found in path, bootstrapping...\n"
+    output ""
+    output "'$1' not found in path, bootstrapping..."
+    output ""
     install_freckles "$using_sudo"
-    echo
-    echo "Bootstrapping finished, running freckles..."
-    echo
+    output ""
+    output "Bootstrapping finished, running '$1'..."
+    output ""
     add_freckles_path
-    echo "Starting 'freckles' with arguments: $@"
-    echo
+    output "Starting '$1' with arguments: $@"
+    output ""
 fi
 
-execute_log "echo Finished freckles bootstrap: `date`" "Error"
+execute_log "echo Finished '$PROFILE_NAME' bootstrap: `date`" "Error"
 
 if [ $using_sudo == true ]; then
-    exec sudo -u "$FRECKLES_USER" -i "PATH=$PATH:$FRECKLES_PATH" freckles "$@"
+    exec sudo -u "$FRECKLES_USER" -i "PATH=$PATH:$FRECKLES_PATH" "$@"
 else
-    PATH="$PATH:$FRECKLES_PATH" freckles "$@"
+    PATH="$PATH:$FRECKLES_PATH" "$@"
 fi
